[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
remappings = [
    "@ethereum-attestation-service/eas-contracts/=lib/eas-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.fmt]
line_length = 100
